// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/categorias": {
    params: {};
  };
  "/cartao": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/categorias" | "/cartao";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/categories.tsx": {
    id: "routes/categories";
    page: "/categorias";
  };
  "routes/card-settings.tsx": {
    id: "routes/card-settings";
    page: "/cartao";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/categories": typeof import("./app/routes/categories.tsx");
  "routes/card-settings": typeof import("./app/routes/card-settings.tsx");
};